# Generated by Django 4.2.7 on 2024-02-13 10:42

import Book_site.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book_site', '0004_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name_plural': {Book_site.models.Series: 'Series'}},
        ),
    ]
