# Generated by Django 4.2.7 on 2024-02-13 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book_site', '0005_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name_plural': 'Series'},
        ),
    ]
