# Generated by Django 4.2.7 on 2024-02-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book_site', '0006_alter_book_options_alter_series_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='series',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
