# Generated by Django 4.2.7 on 2024-02-22 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Book_site', '0007_alter_series_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='series',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='Book_site.series'),
        ),
        migrations.AlterField(
            model_name='series',
            name='series',
            field=models.CharField(max_length=200),
        ),
    ]
