# Generated by Django 4.2.7 on 2024-03-06 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book_site', '0008_alter_book_series_alter_series_series'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={},
        ),
        migrations.RenameField(
            model_name='series',
            old_name='series',
            new_name='name',
        ),
    ]
