# Generated by Django 4.2.7 on 2024-03-06 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book_site', '0009_alter_series_options_rename_series_series_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='name',
            new_name='series_name',
        ),
    ]
